easy_admin:
    entities:
        # List the entity class name you want to manage
        Tag:
          class : App\Entity\Tag
          form:
            fields:
              - {property: "name"}
              - {property: "slug"}